---
abstract: 'Object oriented interface to CSS stylesheets'
author:
  - 'Simone Cesano <scesano@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Tiny-Style
provides:
  CSS::Tiny::Style:
    file: lib/CSS/Tiny/Style.pm
    version: v0.0.3
  CSS::Tiny::Styles:
    file: lib/CSS/Tiny/Styles.pm
    version: v0.0.3
requires:
  CSS::Tiny: 0
  Carp: 0
  Test::More: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.3
